name:                hauth
version:             0.1.0.0
github:              "felbit/hauth"
license:             BSD3
author:              "Martin Penckert"
maintainer:          "martin.penckert@gmail.com"
copyright:           "2019 Martin Penckert"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/felbit/hauth#readme>

dependencies:
- base
- classy-prelude
- mtl
- time
- pcre-heavy
- data-has
- string-random
# Logging
- katip
# PostgreSQL Database
- resource-pool
- postgresql-simple
- postgresql-simple-migration
- exceptions

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- QuasiQuotes
- ConstraintKinds
- FlexibleContexts
- GeneralizedNewtypeDeriving
- TemplateHaskell

library:
  source-dirs: src

executables:
  hauth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hauth

tests:
  hauth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hauth
